WIP Adding more unit tests
Lomadriel/WaitFreeHashMap pull request #27
Opened 2018-12-16 03:52 UTC by Lomadriel

- [x] Test with a key bigger than std::size_t
- [ ] Multi thread tests

2018-12-16 04:21 UTC, Lomadriel commented
Can't build until #26 is merged.

2019-01-08 23:14 UTC, Lomadriel commented
Seems ready to merge.

2019-01-08 23:58 UTC, CBenoit requested changes

2019-01-08 23:58 UTC, CBenoit commented on include/wfc/unordered_map.hpp
> +		return node_union{new /*(std::align_val_t{8})*/ node_t{hash, key, value}};
Why? Should we open an issue?

2019-01-08 23:58 UTC, CBenoit commented on tests/unordered_map/multi_thread_test.cpp
> +				if (map.update(static_cast<unsigned char>(j), 2 * (j + 1), j + 1) != wfc::operation_result::success)
You can use `fail` helper. Same goes for other tests.

2019-01-08 23:58 UTC, CBenoit commented on tests/unordered_map/multi_thread_test.cpp
> +			//printf("j: %zu, n: %zu\n", block_low(i, nbr_threads, map_size), block_high(i, nbr_threads, map_size));
To remove.

2019-01-08 23:58 UTC, CBenoit commented on tests/unordered_map/single_thread_test.cpp
> +bool operator==(const FatKeyHash& a, const FatKeyHash& b);
Check clangformat just to be sure.

2019-01-09 00:44 UTC, Lomadriel commented on include/wfc/unordered_map.hpp
> +		return node_union{new /*(std::align_val_t{8})*/ node_t{hash, key, value}};
Corrected

2019-01-09 00:55 UTC, CBenoit approved these changes

2019-01-09 00:56 UTC, merged